### PR TITLE
[WIP, do not merge] Add a tool to package python function apps

### PR DESCRIPTION
**Pull request by elprans**
Issue: #132

### CODE REVIEW

**Comment by ahmelsayed** [comment]
@elprans running the pack tool on this requirements.txt 

```
azure-functions==1.0.0a1
azure-functions-worker==1.0.0a3
cycler==0.10.0
grpcio==1.12.1
grpcio-tools==1.12.1
kiwisolver==1.0.1
matplotlib==2.2.2
numpy==1.14.5
protobuf==3.6.0
pyparsing==2.2.0
python-dateutil==2.7.3
pytz==2018.5
six==1.11.0
```
results in this error 

```
Traceback (most recent call last):
  File "/tmp/packapp/pack_venv/lib/python3.6/site-packages/distlib/metadata.py", line 731, in __init__
    self._data = json.loads(data)
  File "/home/ahmed/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/ahmed/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ahmed/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../packapp/pack.py", line 208, in <module>
    main()
  File "../packapp/pack.py", line 36, in main
    find_and_build_deps(args)
  File "../packapp/pack.py", line 118, in find_and_build_deps
    wheel.install(paths, maker)
  File "/tmp/packapp/pack_venv/lib/python3.6/site-packages/distlib/wheel.py", line 642, in install
    dist = InstalledDistribution(p)
  File "/tmp/packapp/pack_venv/lib/python3.6/site-packages/distlib/database.py", line 555, in __init__
    metadata = Metadata(fileobj=stream, scheme='legacy')
  File "/tmp/packapp/pack_venv/lib/python3.6/site-packages/distlib/metadata.py", line 742, in __init__
    scheme=scheme)
  File "/tmp/packapp/pack_venv/lib/python3.6/site-packages/distlib/metadata.py", line 284, in __init__
    self.read_file(fileobj)
  File "/tmp/packapp/pack_venv/lib/python3.6/site-packages/distlib/metadata.py", line 384, in read_file
    self.set_metadata_version()
  File "/tmp/packapp/pack_venv/lib/python3.6/site-packages/distlib/metadata.py", line 290, in set_metadata_version
    self._fields['Metadata-Version'] = _best_version(self._fields)
  File "/tmp/packapp/pack_venv/lib/python3.6/site-packages/distlib/metadata.py", line 166, in _best_version
    raise MetadataConflictError('Unknown metadata set')
distlib.metadata.MetadataConflictError: Unknown metadata set
```

**Comment by elprans** [comment]
This bug is fixed in the unreleased `distlib` version.

`pip install -U 'git+https://github.com/vsajip/distlib.git@15dba58a827f56195b0fa0afe80a8925a92e8bf5'` helps

**Comment by ahmelsayed** [comment]
yep, that worked. Thanks @elprans

**Comment by ahmelsayed** [comment]
is it safe to just always run that pip install on the user's venv?

**Pull request closed without merging**
