### PR TITLE
Merge dev branch into master.

### PR DESCRIPTION
**Pull request by 1st1**
The `dev` branch now has a complete Python worker implementation along with unit and integration tests. 

**Features:**

* full support for the following bindings: `httpTrigger`, `timerTrigger`, `queueTrigger`, `blobTrigger`, `http`, `blob`, `queue`;

* support for `context` argument;

* transparent support of the `logging` module; the worker implementation makes sure that `invocation_id` is attached to `RpcLog` messages when possible;

* `out` bindings;

* asynchronous (`async def`) functions are fully supported;

* synchronous functions are executed in a thread-pool, which allows the worker to be responsive to requests from WebHost and execute asynchronous functions in parallel;

* functions are thoroughly validated when loaded: argument names must match those in `function.json`; type annotations, if present, are checked to match binding types in `function.json`;

* the `docs` directory contains the documentation (buildable by Sphinx or ReadTheDocs) for all datatypes as well as usage examples;

* `python setup.py` can be used to automatically download the WebHost image, as well as for generating gRPC Python bindings and running tests;

* integration tests launch a WebHost instance and test against it using AzureWebHostStorage keys;

* unittests include a mock-WebHost gRPC server that allows to test scenarios that otherwise are not possible to test with real WebHost (like logging, `timerTrigger`, and graceful handling of unsupported gRPC messages);

* `azure.worker` package hosts the worker implementation; `azure.functions` package hosts ABCs and concrete implementations of types like `HttpResponse`.

* the code is type annotated and automatically checked with `mypy` in unit tests;

* the code is PEP 8, which is enforced by a flake8 unit test;

* fully configured AppVeyor and Travis CI integrations.

Please also check out these two wiki entries: [Setting up development environment](https://github.com/Azure/azure-functions-python-worker/wiki/Setting-up-development-environment) and [Worker Architecture](https://github.com/Azure/azure-functions-python-worker/wiki/Worker-Architecture).

### CODE REVIEW

**Comment by 1st1** [comment]
@christopheranderson @pragnagopa as we discussed yesterday on the call, I've created this PR for todays code review.

Also, please **do not** use the "Squash and merge" option.  We'd like to preserve individual commits for `git blame` and `git log` to work.

**Comment by 1st1** [comment]
@christopheranderson Please take a look, I've done the renames.

I also squashed a few commits and removed merge commits so the commit number went down from 68 to 54.

**Comment by pragnagopa** [comment]
🚢!

**Comment by 1st1** [comment]
@christopheranderson Chris, could you please take another look at this PR? I need merge it in order to continue working in the `dev` branch.

**Pull request merged**
