### PR TITLE
NuGet for per-platform worker run environments

### LINKED ISSUE #286: Create a nuget package with the worker that can be included in the runtime build
Today [node, powershell, and java ](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/WebJobs.Script.csproj#L38-L40) all have nuget packages that put the right files for their workers under `/workers/` when building `azure-functions-host` repo. The python worker is the only one that doesn't do that, causing the build process for CLI, and Docker to explicitly download the worker from github to bundle with the runtime. 

The pros of that approach is that building a given release or commit of the runtime, will bring in the correct worker automatically without having to maintain a separate mapping of which worker goes with which runtime version.

### PR DESCRIPTION
**Pull request by maiqbal11**
Fixes #286 

Generate environments for running the Python worker in Mac, Windows and Linux. 

The NuGet would provide the following structure:

```
PythonWorkerRunEnvironments
  Windows
    .env
    worker
      python
      azure
  Linux
    .env
    worker
      python
      azure
  Mac
    .env
    worker
      python
      azure
```

### CODE REVIEW

**Comment by maiqbal11** [comment]
Closing favor of https://github.com/Azure/azure-functions-python-worker/pull/329 so we can get a CI build with proper artifacts.

**Comment by maiqbal11** [comment]
\cc @asavaritayal

**Comment by maiqbal11** [comment]
Ping. @ankitkumarr, @ahmelsayed, can we get some confirmation if the core-tools are able to consume the generated artifacts? Getting the changes needed for core-tools into a PR would be ideal.

**Comment by ankitkumarr** [comment]
@maiqbal11, please let me know once the artifacts are in myget (discussed offline). I can update core-tools build script to consume them and test it out.

**Comment by maiqbal11** [comment]
> @maiqbal11, please let me know once the artifacts are in myget (discussed offline). I can update core-tools build script to consume them and test it out.

I've published the NuGet to the App Service Staging feed. You can start consuming it from there.

**Comment by maiqbal11** [comment]
@ankitkumarr, l believe this should be the final form of the packaging and publishing. Can you confirm if this works for you from the feed and we can close this?

**Comment by ankitkumarr** [comment]
@maiqbal11 thanks for updating the PR. I will verify with our build today and report back.

**Comment by ankitkumarr** [comment]
@maiqbal11, Would it be better if instead of placing the worker code in `workers\python\Windows\python`, we just placed them `workers\python\Windows`? It avoids an additional step in the core-tools build process.

**Comment by maiqbal11** [comment]
> @maiqbal11, Would it be better if instead of placing the worker code in `workers\python\Windows\python`, we just placed them `workers\python\Windows`? It avoids an additional step in the core-tools build process.

I've made the change so that `worker.py` and `worker.config.json` are copied directly to the Windows etc. folders with the python folder. Once the PR gets checked in to dev, you can get the the latest version of the NuGet package from the feed. To verify the latest change, you can use the Artifacts tab on the CI page.

**Comment by maiqbal11** [comment]
@ankitkumarr, we should no longer need https://github.com/Azure/azure-functions-core-tools/pull/900, right?

**Comment by ankitkumarr** [comment]
@maiqbal11, yes we shouldn't need that. I will close that PR once we merge and verify everything using nuget package.

**Comment by maiqbal11** [comment]
Removing publish step to NuGet in favor of release pipeline - will add Wiki notes on how this can be accomplished.

**Pull request merged**
