### PR TITLE
Add release instructions

### PR DESCRIPTION
**Pull request by elprans**

### CODE REVIEW

**Comment by elprans** [comment]
> Can you add info on where and how to update the functions Runtime version

It's specified here: https://github.com/Azure/azure-functions-python-worker/wiki/Contributor-Guide#setting-up-development-environment

**Comment by elprans** [comment]
By the way. I can add this information to the Wiki instead. @pragnagopa?

**Comment by pragnagopa** [comment]
Yes. Lets add this to the wiki.

**Comment by elprans** [comment]
Done.

**Pull request closed without merging**
