### PR TITLE
Update grpc dependencies

### PR DESCRIPTION
**Pull request by pragnagopa**

### CODE REVIEW

**Comment by maiqbal11** [comment]
The CI is failing because there appears to be some error with installing grpc dependency. I'll take a look at what's going on.

**Comment by maiqbal11** [comment]
@pragnagopa, is this still the version of grpc you want to use?

**Comment by pragnagopa** [comment]
1.19.0 is latest. Please move to the latest.

**Comment by maiqbal11** [comment]
@pragnagopa, looks good?

**Pull request merged**
