### PR TITLE
Adding .NET install to yaml

### PR DESCRIPTION
**Pull request by fabiocav**

### CODE REVIEW

**Comment by pragnagopa** [comment]
@elprans - 2.1 is the latest dotnet version see here https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/csharp.rb#L418 , which is now 2.1.300

**Comment by elprans** [comment]
@pragnagopa Not 2.1.300-final, though, only the -preview build has been published: see: https://travis-ci.org/Azure/azure-functions-python-worker/builds/412874129#L716

**Comment by elprans** [comment]
> `dotnet --version`
> `2.1.300-rc1-008673`

**Comment by pragnagopa** [comment]
Let's try switching to AppVeyor first. If we still need travis, please create an issue here: https://github.com/travis-ci/travis-build/

**Comment by fabiocav** [comment]
Based on the new logic, 2.1 is supposed to be interpreted as the latest 2.1 version, which technically is supposed to be 2.1.2 runtime/2.1.302 SDK. Based on what I'm seeing though, people have not been successful with a Travis CI setup without an explicit install step, which is what I've pointed to in the other PR (and what we use in our runtime CI builds)

**Comment by fabiocav** [comment]
@elprans still curious, what was the problem (if there was one) with the explicit installation step we mentioned in the other PR?

**Comment by pragnagopa** [comment]
@elprans  - Can you try the install script https://github.com/Azure/azure-functions-host/blob/dev/dotnet-install.sh ?

**Comment by elprans** [comment]
Install script works. I integrated it with other CI fixes in #173. Thanks!

**Comment by fabiocav** [comment]
Good to hear! Thank you!

**Pull request closed without merging**
