### PR TITLE
Move 'tests/functions' to 'tests/http_functions'

### PR DESCRIPTION
**Pull request by 1st1**
As suggested by @pragnagopa it would make it easier for us
to navigate through the test suite once we have tests for
timer- and queue- triggered functions.

### CODE REVIEW

**Comment by asavaritayal** [comment]
Per my offline discussion with Chris and Pragna, we'll do the final code review on merge to master. Merging the current PR for now.

**Comment by 1st1** [comment]
> Per my offline discussion with Chris and Pragna, we'll do the final code review on merge to master. 

In this case, can we just push to the dev branch directly? Or do you guys want us to create PRs?

**Comment by pragnagopa** [comment]
Let's keep creating PRs - mostly to follow best practices and it will give us a chance to keep an eye on the changes that are going to be merged.

**Comment by 1st1** [comment]
Yep, agree.

**Pull request merged**
