### PR TITLE
Restore compatibility with pre-b1 releases of worker in worker.py

### PR DESCRIPTION
**Pull request by elprans**
Fixes: #246

### CODE REVIEW

**Comment by maiqbal11** [comment]
We can hold off on this fix for now. @ahmelsayed is going to try to change the `PYTHONPATH` so that we reference the version of the worker we install on the image rather than using the version that the user provides.

**Comment by ankitkumarr** [comment]
@maiqbal11, I think we still may need this change to ensure compatibility with older versions of the CLI.

**Comment by maiqbal11** [comment]
> @maiqbal11, I think we still may need this change to ensure compatibility with older versions of the CLI.

Older versions of the CLI should be using the previously released versions of the `worker.py` and `worker.config.json`. The `PythonWorkerUrl` and `PythonWorkerConfigUrl` variables in the settings pick these up based on the release. For example, the previous `worker.py` in `1.0.0a6` (https://raw.githubusercontent.com/Azure/azure-functions-python-worker/1.0.0a6/python/worker.py) is still available for previous CLI versions. I believe this should ensure compatibility in older CLI versions. Was this the concern that you had or is it something different?

**Comment by ankitkumarr** [comment]
@maiqbal11, 
My concern is about older apps trying to publish with `--build-native-deps`. Say, some app with dependency on a6 tries to publish, we will pull the newest Docker image (with b1) and package their app inside it. While packaging, we may be trying to bundle the new `worker.py` with their venv's old versions of `azure-functions-worker` (a6). Given that new `worker.py` is incompatible with the old `azure-functions-worker`, they may face issues.
Does that make sense?

**Comment by maiqbal11** [comment]
> @maiqbal11,
> My concern is about older apps trying to publish with `--build-native-deps`. Say, some app with dependency on a6 tries to publish, we will pull the newest Docker image (with b1) and package their app inside it. While packaging, we may be trying to bundle the new `worker.py` with their venv's old versions of `azure-functions-worker` (a6). Given that new `worker.py` is incompatible with the old `azure-functions-worker`, they may face issues.
> Does that make sense?

@asavaritayal , this is a valid concern about breaking existing customers since we'll be using the worker installed in the base image going forward which could be incompatible with the one the from the previous releases. Can we post an announcement regarding this?

**Comment by elprans** [comment]
@maiqbal11 AFAIK we have not made any breaking changes for a while, so existing functions should work with the new worker versions without an issue.

**Comment by maiqbal11** [comment]
Merging this is in as we'll need it to do a new release with the fixes that were in `1.0.0b1` but were rolled back.

**Pull request merged**
