### PR TITLE
[do not merge]Include worker.config.json in distribution metadata

### PR DESCRIPTION
**Pull request by elprans**
`worker.config.json` is now included in the worker package distribution
metadata, and can be accessed like this:

    import pkg_resources
    dist = pkg_resources.get_distribution('azure-functions-worker')
    worker_config = dist.get_metadata('worker.config.json')

Fixes: #243
Requires: https://github.com/Azure/azure-functions-host/pull/3369

### CODE REVIEW

**Comment by pragnagopa** [comment]
I have assigned this to myself. Will merge it in after runtime changes roll out.
Cc @maiqbal11 @asavaritayal

**Comment by pragnagopa** [comment]
Functions Runtime version  2.0.12210 which is in production now, requires  `defaultWorkerPath`.  New `worker.config.json` cannot be used until the latest changes in runtime roll out.

**Comment by pragnagopa** [comment]
It would be confusing to have two copies. Please delete https://github.com/Azure/azure-functions-python-worker/blob/master/python/worker.config.json. Once function runtime rolls out, 
- Publish changes to PyPI ( this will include worker.config.json)
- Update CLI 
- Udpate Docker

**Comment by elprans** [comment]
@pragnagopa I pushed an updated version with a reference to a pre-release host build that includes https://github.com/Azure/azure-functions-host/pull/3369 so that CI can work.

**Comment by elprans** [comment]
@pragnagopa Can we merge this?

**Comment by maiqbal11** [comment]
Closing this in favor of NuGet packaging: https://github.com/Azure/azure-functions-python-worker/pull/329

**Pull request closed without merging**
